import platform, shutil

e = Environment()

if(platform.system() == "Linux"):
   e.Append( CPPFLAGS = '-Wall -pedantic -pthread -Wno-long-long -I include -std=c++11' )
   e.Append( LINKFLAGS = '-Wall -pthread' )
   e.Append( CPPPATH = ['/usr/include/python3.8'] )
   e.Append( LIBPATH = ['/usr/lib/python3.8'] )
   e.Append( LIBS = [ 'boost_python38' ] )
   target = 'build/map_module.so'
else:
   print(platform.system() + " not supported")

def build_link_to_lib( target, source, env):
   '''tworzy link (symboliczny) do biblioteki - uzywany w serwerze'''
   shutil.copy( str(source[0]), str(target[0]) )
   return

dll = e.SharedLibrary(source = ["src_cpp/Agents_Map.cpp", "src_cpp/City.cpp", "src_cpp/Agent.cpp"], target = "build/map_module")
e.Command(target, dll, build_link_to_lib )
